repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
  - hooks:
      - id: php-lint
      - args:
          - --standard=PSR1/,./phpcs.xml
          - -p
        exclude: (examples|test)
        files: \.(php)$
        id: php-cs
      - id: php-unit
    repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
